### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by sickk5** [bnmnetp/runestone#547]
After I log in I can do the first page in the General Introduction and 'Complete' it, but when I move forward to the next page I am no longer logged in. The pages that have the interactive questions I have answered I am not allowed to check because I am not logged in. I am not sure how to stay logged in so I can make some progress.

**Comment by asdfhjkl** [comment]
I have the same problem. I can only login via password reset. After that my password isn't accepted anymore.

**Comment by bnmnetp** [comment]
Please make sure you are using your username (such as sickk5) and not your email address when you log in.
