### ISSUE TITLE
Firefox not handling hidden activecode

### ISSUE THREAD

**Issue by presnick** [bnmnetp/runestone#548]
I am using ==== to put some test cases at the end of code exercises. It's working fine in Chrome, but the extra code doesn't seem to be executed in Firefox.

https://programsinformationpeople.org/runestone/static/umsi106w15/Assignments/ps1.html#problem-set-1

Here's a snippet from https://raw.githubusercontent.com/presnick/runestone/master/pip2/source/Assignments/ps1.rst
that's generating the first activecode window.

.. activecode:: ps_1_1

   tpa = 0
   
   ====
   import test
   print "\n\n---\n"
   test.testEqual(tpa, 6)

**Comment by bnmnetp** [comment]
Hi Paul,

I'm in Vietnam until Jane and I get settled in to our flat in Malta for the spring semester.  I'll be able to look at this at the end of January, once we are settled.

Brad
