### ISSUE TITLE
Python activecode turtle output broken.

### ISSUE THREAD

**Issue by lrowe** [bnmnetp/runestone#554]
Clicking "run" on the [visualizing recursion examples](http://interactivepython.org/runestone/static/pythonds/Recursion/graphical.html) just prints the code unformatted where I would expect to see the turtle output.

Pasting the code into http://www.skulpt.org/ works.

**Comment by bnmnetp** [comment]
@lrowe,  Is this for a course that you built yourself?  My guess is that it is, and that it needs to be rebuilt.  We had a lot of problems like this early last fall, in all cases a rebuild of the course fixed it.

Brad

**Comment by lrowe** [comment]
Sorry, missed your comment before. This is on the interactivepython.org site.
