### ISSUE TITLE
Register error, Sorry, Something went wrong  The error is: invalid request

### ISSUE THREAD

**Issue by DougHuffman** [bnmnetp/runestone#557]
Register error, Sorry, Something went wrong  The error is: invalid request.  For any other error, please report this on our github page (github account required).

**Comment by bnmnetp** [comment]
What course were you trying to register for?  What did you enter for the course name?

**Comment by DougHuffman** [comment]
I specified no course for not having yet reviewed the offerings.  I am
reading Problem Solving with Algorithms and Data Structures
<http://interactivepython.org/runestone/static/pythonds/index.html> and it
appears that I am logged in despite the errors.

It was not my intention to disturb your travels.  Thanks for your attention
and response.

**Comment by Firecage** [comment]
Thanks @DougHuffman You linking that fixed the same problem for me!
