### ISSUE TITLE
assignment sort

### ISSUE THREAD

**Issue by mhaugrud** [bnmnetp/runestone#570]
When viewing student submissions for an assignment, I would find it helpful to have the students sorted by name. It doesn't matter to me if it is by first or last name. Currently there is no order that I can discern.

**Comment by bnmnetp** [comment]
Hi, which URL are you using?  When I see the list of students they are sorted.

Brad

**Comment by bnmnetp** [comment]
Oh, Nevermind.  Just fixed it.

**Comment by mhaugrud** [comment]
thanks
