### ISSUE TITLE
2-Dimensional Iteration: Image Processing

### ISSUE THREAD

**Issue by tiaanroelofswart** [bnmnetp/runestone#571]
In iter-9-2: In the previous ActiveCode example, what are the RGB values of the pixel at row 100, column 30 it has the wrong answer compared o the ActiveCode output

**Comment by bnmnetp** [comment]
Interesting, I get different values for different browsers:

```
Firefox:  183 179 170  -- right on
Mobile Safari:  183 179 170
Chrome: 184 178 171
Safari:  183 178 171
```

I'll have to look into it a bit more.  My hypothesis is that it is differences in how the images are rendered since we are getting the pixel values out of the canvas after rendering, not directly from the file.

**Comment by tiaanroelofswart** [comment]
I didn't even think of different browsers and different canvas rendering. Good to know though thanks.
