### ISSUE TITLE
"mark as completed button" on AVL tree implementation page does not work.

### ISSUE THREAD

**Issue by alagram** [bnmnetp/runestone#575]
Tiny bug here... the 'mark as completed' button on the AVL tree implementation page does not do it job. i.e when I click on the button, nothing happens.

**Comment by bnmnetp** [comment]
I just tried it here:  http://interactivepython.org/runestone/static/pythonds/Trees/AVLTreeImplementation.html

And it worked just fine.  If you know how to check your javascript console in your browser can you do that?  As well as give me some more information about the browser you are using, version, etc.

**Comment by alagram** [comment]
Ah ok. I'm using chrome Version 41.0.2272.104 (64-bit). [Here](https://www.dropbox.com/s/id0hp1n7r12giet/vrLke.png?dl=0) is a screenshot of the javascript console.

**Comment by alagram** [comment]
btw I've since tried on other machines with the same result - when I click the button, nothing happens.

**Comment by alagram** [comment]
Works now. Thanks!
