### ISSUE TITLE
OpenID 2.0 deprecated

### ISSUE THREAD

**Issue by mdolezel** [bnmnetp/runestone#583]
Google no longer accepts login using OpenID 2.0. You should migrate google login option to OpenID Connect.

When I try to login to interactivepython.org I get this dialog https://support.google.com/accounts/answer/6206245?p=openid&rd=1&hl=en

**Comment by bnmnetp** [comment]
Hi,  I use the Janrain service for all of the social logins.  I thought the migration was supposed to happen automatically.  I have configured google+ and am hoping that will take care of the problem.

**Comment by bnmnetp** [comment]
OK, the version of web2py we are using online needed a new plugin to work with the new googleplus login option in Janrain.

For the record, I copied the janrain_account.py file from the latest stable release of web2py into the gluon/contrib/login_methods/ folder and changed the import in db.py.

I didn't want to risk a full upgrade of web2py right now.  This seems to have done the trick although you will be forced to reauthenticate as I understand things.
