### ISSUE TITLE
Highlight is not working

### ISSUE THREAD

**Issue by shchen** [bnmnetp/runestone#592]
Hello, 

The highlight feature doesn't pop out after I select the text. It was working for me until a few days ago. The "Last point" feature can't remember the exact paragraph I was reading if i don't highlight text. Could you please look into it? Thanks so much!

SC

**Comment by bnmnetp** [comment]
Hi 

I would be happy to look into this, but you need to give me more information, can you please be as specific as possible about what page you are looking at?  I need the exact URL in  your browsers address bar.  What browser are you using?  What operating system?  what is your username on the website? When was the last time it worked for you?  Are you sure you were logged in?  If  you can get to your browsers javascript console, please copy and paste any messages you see there when you reload the page.

Why do I need all of this information?  I do not have magical powers.  Saying that something does not work gives me almost no information.  Highlighting works just fine for me,  the last place I read works fine.  so if I am going to figure this out, I need to know a lot more about what makes you different from me.

**Comment by shchen** [comment]
Sure, I'm using Chrome and the URL is: http://interactivepython.org/runestone/static/pythonds/SortSearch/Hashing.html?lastPosition=0

My username is "sockchen" and operating system is Mac OS X. I'm sure I'm logged in and I can see the highlights in the pages I reviewed a few days ago. 

There are a few messages in the console:
```
Uncaught TypeError: Cannot read property 'msie' of undefined
rangy-core.js:10 'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach).
```
```
rangy-core.js:10 Discontiguous selection is not supported.(anonymous function) @ rangy-core.js:10
connect.facebook.net/en_US/all.js:64 
```
```
Invalid App Id: Must be a number or numeric string representing the application id.
```
```
jquery.js:5 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
```
```
rangy-core.js:10 Uncaught NotFoundError: Failed to execute 'selectNodeContents' on 'Range': The node provided is null.
```
```follow_button.50005fe33691ad15041f7199457ac3e0.en.html:Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi)
```
```
connect.facebook.net/en_US/all.js: Received message of type object from http://platform.twitter.com, expected a string
```
```
opt-frontend-common.js: Uncaught TypeError: $.doTimeout is not a function
```

Please let me know if you need anything else. Thanks!

**Comment by shchen** [comment]
Everything works well now. Thanks so much!
