### ISSUE TITLE
Pythoninteractive activecode interpreter run window not showing

### ISSUE THREAD

**Issue by winterandnoodle** [bnmnetp/runestone#600]
I press the activecode run button but the gray window isn't showing.

**Comment by bnmnetp** [comment]
Sorry, you need to be a lot more specific about what is happening.  Which page isn't working for you?  Which book are you using?  which activecode are you trying?  Is it happening for all activecodes or just one.

**Comment by winterandnoodle** [comment]
Sorry, I was in a huge rush. The book is "How to Think Like a Computer Scientist
Learning with Python: Interactive Edition 2.0" and the page is An Overview of Runestone Interactive. I used all activecodes but they just show me a closed gray window, and I'm worry that it will do the same thing with if I get to the Notebook.

**Comment by bnmnetp** [comment]
I just checked this page:  http://interactivepython.org/runestone/static/overview/overview.html   and all of the activecodes are working fine.  What browser are you using?  Can you find the javascript console and see if there are error messages there?  

I don't understand what you mean by "get to the Notebook"

**Comment by winterandnoodle** [comment]
I'm using Google Chrome. They're not working for me they were fine at my first time visiting. And how do you open javascript console? By get to the notebook, I mean just the whole Runestone Interactive with Python book.

**Comment by winterandnoodle** [comment]
Nevermind! It's working in another sections but for some reason it didn't work in the overview. But thanks for helping.
