### ISSUE TITLE
incorrect values returned on int division

### ISSUE THREAD

**Issue by seaem** [bnmnetp/runestone#605]
In the Getting Started With Data -> Built-in Atomic Datatypes print(7/3) and print(3/6) return floating point values when viewing the answer using "Run" button. (result in Codelens shows the correct value though). http://interactivepython.org/runestone/static/pythonds/Introduction/GettingStartedwithData.html

"The return type of a division (/) operation depends on its operands. If both operands are of type int, floor division is performed and an int is returned." - Python 2.7 documentation

**Comment by bnmnetp** [comment]
This depends on whether you are using python 2 or 3.  In pythonds we use python3 semantics for division.   In the new version the show in codelens and the activecode examples should be in sync.
