### ISSUE TITLE
Save button warning. 

### ISSUE THREAD

**Issue by arf1910** [bnmnetp/runestone#611]
I took the How to Think Like a Computer Scientist in high-school and what I realized is that when saving code, there is no warning before saving whatever code is in the code space. Me and a few other classmates had hit the save button before hitting the load button on some projects and lost the code we had been working on before. There should be a warning before hitting the save button that asks if you're sure you want to save your code before actually saving the code that's in the code space. If this is too intrusive, then at least have a warning when the code space is empty.

**Comment by bnmnetp** [comment]
You can also see all of your past answers by using the Code Coach button.  This lets you click through the history of your solution.

**Comment by arf1910** [comment]
My teacher created her own page under assignments in that course and I've loaded some code from older projects and the Code Coach doesn't load any of my old code and I actually lost some of my old code from one of the projects. On personal assignments and projects there, the Code Coach doesn't show any of my old code.

**Comment by arf1910** [comment]
![screen shot 2015-07-27 at 12 11 43 pm](https://cloud.githubusercontent.com/assets/13523357/8911199/ed21b662-3458-11e5-9574-48e35ab982f4.png)
![screen shot 2015-07-27 at 12 13 01 pm](https://cloud.githubusercontent.com/assets/13523357/8911202/f01269d4-3458-11e5-8bcc-974e4205f017.png)


Code Coach doesn't load anything from either the personal assignments or the assignments in the course. There seem to be javascript errors but I don't really know much javascript.

**Comment by bnmnetp** [comment]
Not sure why codecoach is not working for you.

In any case I added a warning dialog when you are about to save an empty program.  Thanks for the report.  You won't see that on the site immediately as it will take a bit of time to push that out.

**Comment by iamakimmer** [comment]
thanks so much for the change! this will help a lot of the students out!

**Comment by bnmnetp** [comment]
The fix has been deployed, but will require a rebuild of any current course.
