### ISSUE TITLE
select-2-1: ambiguous/incorrect information

### ISSUE THREAD

**Issue by mbsiff** [bnmnetp/runestone#612]
While selecting that `x > 0 and x < 5` is the correct answer; it needs to be observed that Python does accept `0 < x < 5`. (It can be noted as the book does elsewhere, that it's better to learn the first form as it is consistent with what is legal in other PLs.)

**Comment by bnmnetp** [comment]
Yes, and the feedback when you select ``0 < x < 5`` says that it is correct in Python but not in most other programming languages.  Since this is a book for beginners that are likely to use other languages we decided to go this route.

**Comment by mbsiff** [comment]
Thanks for the prompt reply; I am embarrassed I did not try that answer to
see.
