### ISSUE TITLE
Error message when clicking Instructor Help

### ISSUE THREAD

**Issue by rosewcs345** [bnmnetp/runestone#618]
Sorry, Something went wrong

The error is: invalid request  . . .

Wanted to find out how to delete old class list, but when clicking Instructor Help link got this message instead

**Comment by bnmnetp** [comment]
Hi,

I have restored that page.  It got lost in the reorganization of all of the books.

I need to find a new home for it, so lets keep this open.

**Comment by rosewcs345** [comment]
Sounds like a plan - thanks!
