### ISSUE TITLE
Exercises in "How to Think like a Computer Scientist"

### ISSUE THREAD

**Issue by clairedemars1** [bnmnetp/runestone#621]
This is also for the interactive "How to think like a computer scientist". The exercises stop working for me in the section called "More About Iteration". In earlier exercises, there had been a button available labeled "Show/Hide Code" which opened a screen with space to write the code. In these later exercises, however, this button is not present, and instead there is a little space that looks like it is for coding but which won't let me write anything in it.

**Comment by bnmnetp** [comment]
I just went to this page:  http://interactivepython.org/runestone/static/thinkcspy/MoreAboutIteration/Exercises.html

Can you confirm that this is the same page you are having trouble with?   

For me, all of the exercises on this page have the show/Hide code button and I am able to edit and run them.

I released a new version of the book this morning.  When I do this there are oftentimes some caching problems that linger for a day or so.  If a simple reload does not fix the problem, try a different browser, or clear your cache and see if the problem persists.  If it does persist, then check the javascript console.  Anything in there might be helpful in getting to the problem.

Thanks,

Brad

**Comment by clairedemars1** [comment]
Clearing the cache fixed it, thanks!
