### ISSUE TITLE
Merge sort algorithm

### ISSUE THREAD

**Issue by blossomica** [bnmnetp/runestone#622]
Hello,

I was looking into the "merge sort" code yesterday. The full code was there and looking okay. Sometime in the mid of the day, the code changed and turned into a mix of theory + code. It doesn't run at all now. I was wondering if you can view that bug as well: http://interactivepython.org/runestone/static/pythonds/SortSearch/TheMergeSort.html

image: http://i.imgur.com/4EAN7lm.png

Thank you

**Comment by bnmnetp** [comment]
Thanks for the report.  There was indeed a formatting problem on that page.  Fixed now.

**Comment by blossomica** [comment]
I see.  Thanks :)
