### ISSUE TITLE
Error Creating Course

### ISSUE THREAD

**Issue by dvermes** [bnmnetp/runestone#623]
Traceback (most recent call last):
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/scheduler.py", line 237, in executor
    result = dumps(_function(*args, **vars))
  File "applications/runestone/models/scheduler.py", line 114, in run_sphinx
    populateSubchapter(root, fn, fh, sourcedir, rvars['projectname'])
  File "applications/runestone/models/scheduler.py", line 234, in populateSubchapter
    mo = div_re.match(line)
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/scheduler.py", line 535, in 
    signal.signal(signal.SIGTERM, lambda signum, stack_frame: sys.exit(1))
SystemExit: 1

**Comment by bnmnetp** [comment]
Can you tell me what course you were building?

**Comment by bnmnetp** [comment]
OK, I think it must have been cs925, and I believe I have fixed the problem.

**Comment by dvermes** [comment]
Sorry for the delayed response. Yes, it should have been the cs925 course. Ideally, I was hoping to align that course to Barb Ericsson’s AP Review eBook, but that doesn’t seem to be one of the eBook options…

Thanks,

Doug
On August 12, 2015 at 3:03:44 PM, Brad Miller (notifications@github.com) wrote:

OK, I think it must have been cs925, and I believe I have fixed the problem.

**Comment by bnmnetp** [comment]
Ugh!   Not only did I delete the radio box for Barb's book but I put her name on the wrong book.

I have rectified that now.

You may want to delete cs925 and start over, or choose a different name.

Brad

**Comment by dvermes** [comment]
I just tried doing that. I selected Barb's AP CS review book, created the
course, but then it took me to the homepage for the Problem Solving With
Algorithms and Data Structures book. Did I do something wrong or is it not
linked properly?

Thanks,

Doug

**Comment by bnmnetp** [comment]
The book was built correctly.  But when you deleted the old course, the program automatically drops you into the pythonds book by default.  Try logging out and logging in again, and if it does not take you to the right course then edit your profile and make sure it points to your course.

**Comment by dvermes** [comment]
Aha, that did it! Thanks! Sorry for all the questions. I'm just figuring
out how to site works and seeing how/if I can use it in my Computer Science
classes this fall.

Thanks,

Doug

**Comment by bnmnetp** [comment]
No problem.  I just did a big update to the software last week, and so I'm still squashing bugs before classes start!
