### ISSUE TITLE
New course creation error

### ISSUE THREAD

**Issue by ghillebrand** [bnmnetp/runestone#624]
The error code doesn't include the course name text I used, so I can't be sure what is required - I MAY have included a slash?? Can't remember now.
Will try again.

BTW, thanks for what I believe to be the finest programming course on the web. I teach IT at high school, and have for a number of years, and have tried many approaches - this is mow my preferred one!
Grant H

An error occurred.

An error occurred while building this course. Please check that you entered a valid project name. Project names must not contain spaces or symbols. If you are sure you have entered a valid project name, please submit an error report here. Make sure you include the following traceback information:

Traceback (most recent call last):
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/scheduler.py", line 237, in executor
    result = dumps(_function(*args, **vars))
  File "applications/runestone/models/scheduler.py", line 34, in run_sphinx
    os.mkdir(custom_dir)
OSError: [Errno 2] No such file or directory: '/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/custom_courses/9608/16'

g.hillebrand@isct.co.za | Back to top

© Copyright 2014 Brad Miller, David Ranum

**Comment by bnmnetp** [comment]
Yes, 9608/16   --- slashes are not allowed.  I will add that check to the verifier.
