### ISSUE TITLE
Everyone is getting access to instructor page (?)

### ISSUE THREAD

**Issue by rosewcs345** [bnmnetp/runestone#625]
Had my son sign up for course, also signed myself up using a test account to double-check.
Note that when my son is signed in, he has access to Instructor Page.
When I log in with my test account (to mimic a student signing up), I get the same results.

Did we go about the registration process incorrectly, or is this a bug?
I am including images to show what how we registered and the result.

![register3](https://cloud.githubusercontent.com/assets/715952/9298667/ac9b2438-4480-11e5-8ca4-3ce501b3f2d6.PNG)

![interactivepython](https://cloud.githubusercontent.com/assets/715952/9298676/cee2e0bc-4480-11e5-8fb8-32cb194f6d79.PNG)

**Comment by bnmnetp** [comment]
Yes, everyone can get to the first page, but if he tries to go any deeper he will not be allowed.

Remember that is how you became an instructor, register as a regular user for the thinkcspy course and then go to the instructor dashboard and create your own course.

So, anyone can become an instructor of their own course.  But they will not have access to the data about students in any other course.

**Comment by rosewcs345** [comment]
Thanks for responding so quickly, and sorry for the trouble!

On Mon, Aug 17, 2015 at 7:40 AM, Brad Miller <notifications@github.com>
wrote:

> Yes, everyone can get to the first page, but if he tries to go any deeper
> he will not be allowed.
>
> Remember that is how you became an instructor, register as a regular user
> for the thinkcspy course and then go to the instructor dashboard and create
> your own course.
>
> So, anyone can become an instructor of their own course. But they will not
> have access to the data about students in any other course.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bnmnetp/runestone/issues/625#issuecomment-131791511>.
>



-- 
-- 

*Rose Williams*

*Lecturer*

*Department of Computer Science*

*Binghamton University*

*(607) 777-7702*

*-----------------------------------------------*


*We are what we think.  *

*All that we are arises** with*
* our thoughts.  *

*With our thoughts,** we** make the world.*



*Shakyamuni** Buddha*
