### ISSUE TITLE
Pages Completed show previous as well as current students

### ISSUE THREAD

**Issue by rosewcs345** [bnmnetp/runestone#632]
When I go to Instructor Page and click the Pages Compteted link

Also, can the data in this table be downloaded?  
It's too small to see, even when zoomed in quite a bit

**Comment by bnmnetp** [comment]
No, the data for this is not downloadable.  I can add it to the list.

I can fix the problem with former students showing up.   That is an easy fix to the query.

How many students are in your course?  I made the image sized to what looked fairly reasonable for an average size class, but I suspect you might have a lot more students.  I don't think it would be too hard to resize the height of the image based on the class size.

Brad

**Comment by rosewcs345** [comment]
I'll be having about 60 students this semester
I realize that that will be a great deal of data on one page!
Currently, however, its showing both old and new students (and not all of the new students have signed up yet!)
