### ISSUE TITLE
Compare feature not working

### ISSUE THREAD

**Issue by rosewcs345** [bnmnetp/runestone#638]
I've tried both Chrome and Firefox, but when I complete an exercise and click Check it gives the proper feedback, but when I click Compare, there is no response.  
This always worked before and was extremely useful for seeing how the students were doing.

**Comment by bnmnetp** [comment]
This should be fixed.  When you get a chance rebuild your course and give it a try.  It make take a page refresh or two to make sure you have the newest  javascript file.

**Comment by rosewcs345** [comment]
Thanks once again - it's fine now!

On Wed, Sep 9, 2015 at 9:18 AM, Brad Miller <notifications@github.com>
wrote:

> This should be fixed. When you get a chance rebuild your course and give
> it a try. It make take a page refresh or two to make sure you have the
> newest javascript file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bnmnetp/runestone/issues/638#issuecomment-138906522>.
>



-- 
-- 

*Rose Williams*

*Lecturer*

*Department of Computer Science*

*Binghamton University*

*(607) 777-7702*

*-----------------------------------------------*


*We are what we think.  *

*All that we are arises** with*
* our thoughts.  *

*With our thoughts,** we** make the world.*



*Shakyamuni** Buddha*
