### ISSUE TITLE
Cannot create new course interactivepython 

### ISSUE THREAD

**Issue by shawnmflemingc** [bnmnetp/runestone#642]
New account created (twice, shawnm and smorgan) then when visiting the create new course the webpage sticks on "Building your course" for hours without any page updates. Last time I attempted I left it for 2 hours. Rebuilding course also fails with same never-ending page. 

URL of page stuck is:

http://interactivepython.org/runestone/designer/build?projectname=PSP2015&projectdescription=Fleming+PSP+2015&institution=Fleming+College&coursetype=thinkcspy&loginreq=true&python3=true&instructor=yes&startdate=

**Comment by bnmnetp** [comment]
Sorry, the course building queue got jammed up.  I have restarted it and hopefully things will clear themselves out soon.
